/**
 * Supported Event Types in the Audit Trail domain.
 */
const EVENT_TYPES = {
  SHIPMENT_CREATED: 'SHIPMENT_CREATED',
  LOAD_CONTAINER: 'LOAD_CONTAINER',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  RECORD_TEMPERATURE: 'RECORD_TEMPERATURE',
  TRANSFER_SHIPMENT: 'TRANSFER_SHIPMENT',
  CHANGE_STATUS: 'CHANGE_STATUS'
};

const VALID_EVENT_TYPES = Object.values(EVENT_TYPES);

module.exports = {
  EVENT_TYPES,
  VALID_EVENT_TYPES
};