const EVENT_TYPES = Object.freeze({
  CONTAINER_CREATED: "CONTAINER_CREATED",
  LOADED_ON_SHIP: "LOADED_ON_SHIP",
  CONTAINER_MOVED: "CONTAINER_MOVED",
  TEMPERATURE_SPIKE: "TEMPERATURE_SPIKE",
  ARRIVED_AT_PORT: "ARRIVED_AT_PORT",
});

const VALID_EVENT_TYPES = Object.values(EVENT_TYPES);

module.exports = {
  EVENT_TYPES,
  VALID_EVENT_TYPES,
};